version: '3.3'

services:
  my-mongo:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_DATABASE=my_db_mongo
      - MONGO_INITDB_ROOT_USERNAME=walter
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - '27017:27017'
    volumes:
      - ./mongo_data:/data/db

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=walter
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
