version: '3.3'

services:
  my-mongo:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_DATABASE=my_db_mongo
      - MONGO_INITDB_ROOT_USERNAME=walter
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - '27017:27017'
    volumes:
      - ./mongo_data:/data/db
